// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhUwE2LI8oPjV_ffal6Q6E_a0WDNwqSXo',
    appId: '1:642462261542:web:f398868d7a0a4a2c42a1e7',
    messagingSenderId: '642462261542',
    projectId: 'flutter-notes-fire',
    authDomain: 'flutter-notes-fire.firebaseapp.com',
    storageBucket: 'flutter-notes-fire.firebasestorage.app',
    measurementId: 'G-ZDJGJLGVBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVjo5OMBB5BUmaMaF3hTDI1Jom2TifFw',
    appId: '1:642462261542:android:bc900f3bfe2a7bc642a1e7',
    messagingSenderId: '642462261542',
    projectId: 'flutter-notes-fire',
    storageBucket: 'flutter-notes-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGNdgaDEtV5UfbpFi2P857RREpcRavRg',
    appId: '1:642462261542:ios:81f4326f13c6652a42a1e7',
    messagingSenderId: '642462261542',
    projectId: 'flutter-notes-fire',
    storageBucket: 'flutter-notes-fire.firebasestorage.app',
    iosBundleId: 'com.example.nourRamadan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGNdgaDEtV5UfbpFi2P857RREpcRavRg',
    appId: '1:642462261542:ios:81f4326f13c6652a42a1e7',
    messagingSenderId: '642462261542',
    projectId: 'flutter-notes-fire',
    storageBucket: 'flutter-notes-fire.firebasestorage.app',
    iosBundleId: 'com.example.nourRamadan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhUwE2LI8oPjV_ffal6Q6E_a0WDNwqSXo',
    appId: '1:642462261542:web:f7dd5e6a85c3191642a1e7',
    messagingSenderId: '642462261542',
    projectId: 'flutter-notes-fire',
    authDomain: 'flutter-notes-fire.firebaseapp.com',
    storageBucket: 'flutter-notes-fire.firebasestorage.app',
    measurementId: 'G-LJ9PNPB9P9',
  );

}